### ISSUE TITLE
Very in-complete Wiki

### ISSUE THREAD

**Issue by JFrap** [unpause/TeazelEngine#1]
The wiki can do with some more content.

Currently, we have pages for...

* GameObject https://github.com/JFrap/TeazelEngine/wiki/GameObject
* Material https://github.com/JFrap/TeazelEngine/wiki/Material

**Comment by JFrap** [comment]
Added page for [Materials](https://github.com/JFrap/TeazelEngine/wiki/Material)

**Comment by unpause** [comment]
Working on that constantly.
